export const TOWER_DIGITS = [
  /* 0 */ 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAcAAAAGCAYAAAAPDoR2AAAAAXNSR0IArs4c6QAAADNJREFUGFd1jkEKAEAIAvX/j3bxYGxC3mRkigAkCR2SYIiL8w8XbMPAaG3IaMFW+9D50AMKryP1qt0TyQAAAABJRU5ErkJggg==',
  /* 1 */ 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAcAAAAGCAYAAAAPDoR2AAAAAXNSR0IArs4c6QAAACtJREFUGFdjZGBg+M8AIv6DKTBgZGSE0BBxhASGJEwHTBGKTvIl0e2EmQQArF0X/qW+nH4AAAAASUVORK5CYII=',
  /* 2 */ 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAcAAAAGCAYAAAAPDoR2AAAAAXNSR0IArs4c6QAAADBJREFUGFdjZGBg+P///38GdMDIyMjACJMBcWAAphgkgqENRZIkY2HGw+3EcBFQAABi2Br4byVrOgAAAABJRU5ErkJggg==',
  /* 3 */ 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAcAAAAGCAYAAAAPDoR2AAAAAXNSR0IArs4c6QAAADBJREFUGFdjZGBg+P///38GdMDIyMjACJMBcWAAphgkAteGbAJYJ7Ikhk6CxuJyEACq8B34iGUYgQAAAABJRU5ErkJggg==',
  /* 4 */ 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAcAAAAGCAYAAAAPDoR2AAAAAXNSR0IArs4c6QAAADVJREFUGFdjZGBg+M8ABf//Q5iMjIwQGiYJk8CQRJZAkfwPlQEZhWEsTBJmLzINtxMkiK4TALbxGv54PU3/AAAAAElFTkSuQmCC',
  /* 5 */ 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAcAAAAGCAYAAAAPDoR2AAAAAXNSR0IArs4c6QAAAC9JREFUGFdj/P///38GHIARJsnIyIihBC6JLgNSDFKOYSzMJqzGwiVBOrG5CWQsAGlmGvgZquD9AAAAAElFTkSuQmCC',
  /* 6 */ 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAcAAAAGCAYAAAAPDoR2AAAAAXNSR0IArs4c6QAAAC5JREFUGFdjZGBg+P///38GdMDIyMjACJMBcTAUYNXGwMCAUyfMGqzGwiXxOQgAXiUd+yiniiwAAAAASUVORK5CYII=',
  /* 7 */ 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAcAAAAGCAYAAAAPDoR2AAAAAXNSR0IArs4c6QAAACtJREFUGFdj/P///38GHICRgYEBQxKmHkMSLsHIyIAiiSwBsgkuiS5BUBIAhWkX+30ZHhIAAAAASUVORK5CYII=',
  /* 8 */ 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAcAAAAGCAYAAAAPDoR2AAAAAXNSR0IArs4c6QAAACZJREFUGFdjZGBg+P///38GdMDIyMjACJMBcWAAphgkQqZOso0FAMHPIPg3G255AAAAAElFTkSuQmCC',
  /* 9 */ 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAcAAAAGCAYAAAAPDoR2AAAAAXNSR0IArs4c6QAAAC9JREFUGFdjZGBg+P///38GdMDIyMjACJMBcWAAphi/JC5jQaaAzMKwEG4sPgcBAG/ZHfXBYqEKAAAAAElFTkSuQmCC',
];
